// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3lThHxhtYuTkMxBNT7PUfXXCo8xdFnKY',
    appId: '1:485782896722:web:b9eb0b8d08811a07d31f8b',
    messagingSenderId: '485782896722',
    projectId: 'mynotes-ab408',
    authDomain: 'mynotes-ab408.firebaseapp.com',
    storageBucket: 'mynotes-ab408.firebasestorage.app',
    measurementId: 'G-R5CXXRE0LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTdAS0jfcOxGSWq5pAZJdSAdQs-_WXkAs',
    appId: '1:485782896722:android:2ec752401698cc42d31f8b',
    messagingSenderId: '485782896722',
    projectId: 'mynotes-ab408',
    storageBucket: 'mynotes-ab408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Q035K7gz5cO9NtFaOhEbDGaOsLHDOak',
    appId: '1:485782896722:ios:bd419f66e3af7d01d31f8b',
    messagingSenderId: '485782896722',
    projectId: 'mynotes-ab408',
    storageBucket: 'mynotes-ab408.firebasestorage.app',
    iosBundleId: 'com.Mydomain.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Q035K7gz5cO9NtFaOhEbDGaOsLHDOak',
    appId: '1:485782896722:ios:bd419f66e3af7d01d31f8b',
    messagingSenderId: '485782896722',
    projectId: 'mynotes-ab408',
    storageBucket: 'mynotes-ab408.firebasestorage.app',
    iosBundleId: 'com.Mydomain.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3lThHxhtYuTkMxBNT7PUfXXCo8xdFnKY',
    appId: '1:485782896722:web:1d34b0720205f41ad31f8b',
    messagingSenderId: '485782896722',
    projectId: 'mynotes-ab408',
    authDomain: 'mynotes-ab408.firebaseapp.com',
    storageBucket: 'mynotes-ab408.firebasestorage.app',
    measurementId: 'G-2RYBQ4YVNZ',
  );

}